language: python
script: bash scripts/gh_conf.sh
branches:
  only:
  - master
env:
  global:
    secure:fcaD1vm1fqzwfPRtCwrPTL1J0NKfFkOe7SeSdwABlI1pNP7XJeu3HsbT7B+VpFt6kYNr6OxqtQ5LU5YxhMPIvsk9Q+vRQns6G0o7KbJFwLE+Qmpv3DnugE0QpGAT5yQhO+UI4Kn8Y6vJiPULGkNw92HOEwljV3/wxMSaetHKyGP3qjT+XbwbU+n/StMFzpVKGEUEyzORNedXB2CCHJQOydDXD924zh0Ujusx36vEnPTZdgUNLU5XDXtbm6ZhLqWTlja1sAQ1c2ANspoCghq4Sgb3D0XieVzB2ykkWG848ZJYkgCMJyl2dpM9a2tcCr/e0ieJhBGPWJxUtkVs0uvsThznNYVWmCnqvbmi8MFuX0WlXNsyeMPPu1Gi8O25bbpTA6ycRJ9iJIR47zYI+oVISrh0fmWKmSAIxE6MNZWrLvR4joyYOUxSJ3i6Hfqj5FZoLsbM/xNXaRXHc1hGzUUg/MGPKMg4Iy7akzN4FEMslcRf1atSZGqGwg5uZ45vFQOrKdjC3vdh9nBgOauhuHD54vk2KprRPlJiqY3Wp1wyRQfFsWNS2qGt9VsoGyGvYf2hePIF+R9UzaDrTm0xoNsFXRiOS755QeEE4HVXgcd1i+4IszV5YbNiQXXZwsmcnKVlp6x11qvHzkeD8d/nbnBV+DfT34SOnYgyde+zg+QfS3U=
