language: python

script: bash scripts/deploy_ghpages.sh

branches:
  only:
  - master

env:
  global:
    secure: fTBQoVVKizF8PrkaLqqhDviZX3OEmky1cc+cra6IhVqSpHuMb4Oq9NTFe4EWZRA8lEZzvLMXtzK5qTg8p16x1KHFTba9M3RFVcz1DPrKqO0XikPf3MJ3EWnMPTtVM8l9YLvwyG+WvquxxT79rIysUTq5L/LUKFE/icr5ZZqWBRk84Sf6J02s6WrtaiFbpaLL3QzD33UHAHVL5ZEWxgfB3tWgtBzQlhaHKbwQOknsOMHRkJylmErqYQLs9k7TCgZNezafqMHbt10RbvvHAKY4QjfN/y7YJZH6ZM3n0sXCh1w7yEQxgOl46Y0nFPOgIzLVKsgV3x4dEiWpuWiL0Tmdx/k2gSqIU4Aac8MyX44L/8JIca8R+hJtxIQX3XlRPj9aD/B9fp1LEqAxs3Jvz97DXYECBoeuUuZXhsXE46Z84K0cS4RIQmzuDPyqGCqXkb/o3BmF7ZCuK7tzyGOaNhuSHyGPgRKF+wI/hn12WYTzg71JnAjCseFrRsJPJGvG3h/xMm0S9lNrsgKhbLLTNkblZJ5Gn8g4yNk44lDfn4JWOSyGlwAOns3hlO4HLYVyGz4Ln9GPYDx+lNRPOKcqM0NWOPbkf4nssmICK+gIH4AhpwCQ5uMB4wY63w2zXVbJaD7CtTQC6mzX9saVtVcPXeBl85u+uY21IGql2XnWgLij4Nk=
